FROM continuumio/anaconda3:2021.05

RUN apt-get -y update --fix-missing
RUN apt-get -y install python3-pip

RUN conda update conda
RUN conda install -c conda-forge dash=1.20.0
RUN conda install -c conda-forge flask-caching=1.7.1
RUN conda install -c conda-forge ipdb

RUN pip3 install yfinance

WORKDIR /SimpleDashboard
ADD . /SimpleDashboard
ENTRYPOINT ["python"]
CMD ["SimpleDashboard.py"]
